<a href="https://colab.research.google.com/github/ninadcpa/DSC540/blob/main/Week1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DSC550 Week 1 Exercise
@author Ninad Patkhedkar

In [1]:
# This code is written for mounting code folder checked out from github on google drive
# All assignment code will be maintained inside folder "DSC550"
# Code from book is inside folder "Data-Wrangling-with-Python"

from google.colab import drive
import sys
import os

drive.mount('/content/drive')
sys.path.append('/content/drive/MyDrive/Colab Notebooks/DSC550')
os.chdir('/content/drive/MyDrive/Colab Notebooks/DSC550')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

In [2]:
import numpy as np

sample = np.random.randint(10, 500, size=(10, 50))

In [3]:
import pandas as pd
df = pd.DataFrame(sample)
df.head()

    0    1    2    3    4    5    6   ...   43   44   45   46   47   48   49
0   70  174  143  245  345   12  225  ...  463  310   20  454  405  288   69
1  244   85  209  134  492  464  146  ...  378  166  233  344  413  196  150
2   41  480  130  116  294  365  390  ...  222  380  374  317  251   71  166
3  461   41  101   94  173  481   55  ...  347  217  330  200  399  307   65
4  414  424  217   70  315  499  257  ...  466  282   57  216   48  230  101

[5 rows x 50 columns]

2. Calculate the sum of each row; the sum of each column; and the sum of all entries.

In [4]:
sample.sum(axis=0)

array([2898, 2354, 1977, 2012, 2585, 3407, 1836, 2824, 3162, 1609, 2282,
       2342, 3582, 2774, 2530, 3329, 2168, 2141, 2283, 2831, 2777, 2179,
       2516, 2390, 2928, 2028, 2529, 2424, 2639, 2310, 1618, 2561, 1976,
       2543, 3083, 2182, 2660, 2664, 2518, 2483, 3527, 2350, 2781, 3140,
       2715, 2154, 2983, 2678, 2514, 1718])

In [5]:
sample.sum(axis=1)

array([12557, 12224, 12111, 10445, 13597, 12701, 13313, 14051, 13471,
       12024])

In [6]:
sample.sum()

126494

In [7]:
flat_arr = sample.flatten()

3. Determine the minimum; maximum; average; and standard deviation of all entries.

In [8]:
flat_arr.max()

499

In [9]:
flat_arr.min()

12

In [10]:
flat_arr.mean()

252.988

In [11]:
flat_arr.std()

144.20149741247488

4. Sort the DataFrame: a) sort on column 2; b) sort on row 2

In [14]:
df.sort_values(by=[2],axis=1)

    39   36   31   27   30   0    21  ...   12   37   26   7    1    14   29
0  446  343   51  447  100   70   54  ...  495  363  329  236  174  201   24
1  365  324  480  169  287  244  161  ...  184  495  444  469   85  153  438
2   12   15   21   37   39   41   49  ...  401  447  457  476  480  492  497
3   48   47  292  154  377  461  433  ...  429  119   82  169   41   35  111
4  337   21  482  483  279  414  243  ...  112   37  354  239  424  225   76
5  113  405  286  386  113  453   70  ...  329  220  143  416  456  284  190
6  437  336  140  390   28  422  438  ...  405  108  191  244  277  368  263
7  387  299  194   89   63  117  198  ...  463  180  160  124  323   98  352
8   38  488  424  199  149  414  467  ...  301  334  317   46   34  422   52
9  300  382  191   70  183  262   66  ...  463  361   52  405   60  252  307

[10 rows x 50 columns]

In [15]:
df.sort_values(by=[2],axis=0)

    0    1    2    3    4    5    6   ...   43   44   45   46   47   48   49
3  461   41  101   94  173  481   55  ...  347  217  330  200  399  307   65
2   41  480  130  116  294  365  390  ...  222  380  374  317  251   71  166
0   70  174  143  245  345   12  225  ...  463  310   20  454  405  288   69
5  453  456  163  216   22  259   14  ...  137  194  191  284  328   64   64
1  244   85  209  134  492  464  146  ...  378  166  233  344  413  196  150
4  414  424  217   70  315  499  257  ...  466  282   57  216   48  230  101
6  422  277  244  429  107  162  104  ...  476  462  378  234  346  395  146
8  414   34  247  180  370  382   56  ...  195  142   91  346  259   19  160
9  262   60  259  240  337  469  198  ...  359  366  128  460   67  468  300
7  117  323  264  288  130  314  391  ...   97  196  352  128  162  476  497

[10 rows x 50 columns]